### ISSUE TITLE
Customize CSS options (frozen/read-only background color)

### ISSUE THREAD

**Issue by piotrp88** [DataDog/jupyterlab-freeze#1]
It would be nice to edit the background color of frozen and read-only cells from the Advanced Settings Editor of JupyterLab.
From the repository I saw there are only two CSS variables in the `style/base.css` file, more specifically:

* `--jp-frozen-bg`
* `--jp-readonly-bg`

I tried to override them from the Theme advanced editor but it doesn't recognize these variables.

**Comment by CarlosDominguezBecerril** [comment]
Thanks for the feedback, I will check with my team if they want to work on this 👍

**Comment by y-haidar** [comment]
I have added this feature on the same PR without realizing that the PR was still open 😅. I hope that is okay.

![Image](https://github.com/user-attachments/assets/db7a2675-6435-4f3b-a2c7-0d1e5fd4e252)

I had to change the CSS variable to enable dynamic change, it is now stored in the root like so:

![Image](https://github.com/user-attachments/assets/3fe1f74f-bab7-4922-81e9-99f62e5e9590)

**Comment by CarlosDominguezBecerril** [comment]
Released in version 0.1.1 https://github.com/DataDog/jupyterlab-freeze/pull/7
