### ISSUE TITLE
Freeze/Unfreeze multiple cells

### ISSUE THREAD

**Issue by piotrp88** [DataDog/jupyterlab-freeze#4]
It would be nice to freeze/unfreeze multiple cells. The expected behaviour should be:

1. select multiple cells
2. press the freeze/read-only/unlock button
3. the state of each cell gets updated

**Comment by y-haidar** [comment]
I have added this feature in this fork. I can make a pull request if owner ask.

https://github.com/y-haidar/jupyterlab-freeze

The fork also have the following css "improvements":

While selecting 3 cells:
![Image](https://github.com/user-attachments/assets/5479797c-3ee3-4a57-b5c7-477a3699e876)

No selection:
![Image](https://github.com/user-attachments/assets/af85e0a1-40e9-49d6-8757-9ea44f7c1412)

**Comment by CarlosDominguezBecerril** [comment]
yes, please open a PR and I will try to review it this week 🙏

**Comment by CarlosDominguezBecerril** [comment]
Released in version 0.1.1 https://github.com/DataDog/jupyterlab-freeze/pull/7
